installing_message = "Built by <b>MostlyWhat</b>, Built for <b>128BitBay</b>. Version <b>Beta</b>"

[[packages]]
name = "yuzu Mainline"
description = "Includes frequent updates to yuzu with all the latest reviewed and tested features."
default = false
    [packages.source]
    name = "github"
    match = "^yuzu-windows-msvc-[0-9]*-[0-9a-f]*.tar.xz$"
        [packages.source.config]
        repo = "yuzu-emu/yuzu-mainline"
    [[packages.shortcuts]]
    name = "yuzu"
    relative_path = "yuzu-windows-msvc/yuzu.exe"
    description = "Launch yuzu"
    
[[packages]]
name = "yuzu Early Access (128BitBay)"
description = "Preview release with the newest features for Free by 128BitBay!"
default = true
    [packages.source]
    name = "github"
    match = "^yuzu-early-access-EA[0-9]*.zip$"
        [packages.source.config]
        repo = "Kryptuq/Yuzu-Early-Access-files"
    [[packages.shortcuts]]
    name = "yuzu Early Access"
    relative_path = "yuzu-early-access/yuzu.exe"
    description = "Launch yuzu Early Access"

[[packages]]
name = "yuzu Early Access (PineappleEA)"
description = "Alternative preview release source by PineappleEA!"
default = false
    [packages.source]
    name = "github"
    match = "^Windows-Yuzu-EA-[0-9]*.zip$"
        [packages.source.config]
        repo = "pineappleEA/pineapple-src"
    [[packages.shortcuts]]
    name = "yuzu Early Access (PineappleEA)"
    relative_path = "yuzu-windows-msvc-early-access/yuzu.exe"
    description = "Launch yuzu Early Access (PineappleEA)"