installing_message = "Built by <b>MostlyWhat</b>, Built for <b>128BitBay</b>. Version <b>Charlie</b>"
hide_advanced = true

[authentication]
# Base64 encoded version of the public key for validating the JWT token. Must be in DER format
pub_key_base64 = "MIIBCgKCAQEAs5K6s49JVV9LBMzDrkORsoPSYsv1sCXDtxjp4pn8p0uPSvJAsbNNmdIgCjfSULzbHLM28MblnI4zYP8ZgKtkjdg+Ic5WQbS5iBAkf18zMafpOrotTArLsgZSmUfNYt0SOiN17D+sq/Ov/CKXRM9CttKkEbanBTVqkx7sxsHVbkI6tDvkboSaNeVPHzHlfAbvGrUo5cbAFCB/KnRsoxr+g7jLKTxU1w4xb/pIs91h80AXV/yZPXL6ItPM3/0noIRXjmoeYWf2sFQaFALNB2Kef0p6/hoHYUQP04ZSIL3Q+v13z5X2YJIlI4eLg+iD25QYm9V8oP3+Xro4vd47a0/maQIDAQAB"
# URL to authenticate against. This must return a JWT token with their permissions and a custom claim patreonInfo with the following structure
# "patreonInfo": { "linked": false, "activeSubscription": false }
# If successful, the frontend will use this JWT token as a Bearer Authentication when requesting the binaries to download
auth_url = "https://api.yuzu-emu.org/jwt/installer/"
    [authentication.validation]
    iss = "citra-core"
    aud = "installer"

[[packages]]
name = "yuzu Early Access"
description = "Preview release with the newest features for the supporters."
icon = "thicc_logo_installer__ea_shadow.png"
requires_authorization = true
# puts a "new" ribbon the package select
is_new = true
    [packages.extended_description]
    no_action_description = "Thank you for your support!"
    # Displayed when the package has no authentication for the user
    need_authentication_description = "Click here to sign in with your yuzu account for Early Access"
    # Displayed when the package has an authentication, but the user has not linked their account
    need_link_description = "You are signed in, but you need to link your Patreon account! Click here for more details"
    # Displayed when the package has an authentication, but the user has not linked their account
    need_subscription_description = "You are signed in, but you need to link your Patreon account! Click here for more details"
    # Displayed when the package has an authentication, but the user has not linked their account
    need_reward_tier_description = "You are signed in, but are not backing an eligible reward tier! Click here for more details"

    [packages.source]
    name = "patreon"
    match = "^yuzu-windows-msvc-[0-9]*-[0-9a-f]*.tar.xz$"
        [packages.source.config]
        repo = "earlyaccess"
    [[packages.shortcuts]]
    name = "yuzu Early Access"
    relative_path = "yuzu-windows-msvc-early-access/yuzu.exe"
    description = "Launch yuzu Early Access"


[[packages]]
name = "yuzu"
description = "Includes frequent updates to yuzu with all the latest reviewed and tested features."
icon = "thicc_logo_installer_shadow.png"
default = false
    [packages.source]
    name = "github"
    match = "^yuzu-windows-msvc-[0-9]*-[0-9a-f]*.tar.xz$"
        [packages.source.config]
        repo = "yuzu-emu/yuzu-mainline"
    [[packages.shortcuts]]
    name = "yuzu"
    relative_path = "yuzu-windows-msvc/yuzu.exe"
    description = "Launch yuzu"

[[packages]]
name = "yuzu Early Access (128BitBay)"
description = "Preview release with the newest features for Free by 128BitBay! (Unsupported Currently)"
icon = "thicc_logo_installer__ea_shadow.png"
default = false
    [packages.source]
    name = "github"
    match = "^yuzu-early-access-EA[0-9]*.zip$"
        [packages.source.config]
        repo = "Kryptuq/Yuzu-Early-Access-files"
    [[packages.shortcuts]]
    name = "yuzu Early Access"
    relative_path = "yuzu-early-access/yuzu.exe"
    description = "Launch yuzu Early Access"

[[packages]]
name = "yuzu Early Access (PineappleEA)"
description = "Alternative preview release source by PineappleEA!"
icon = "thicc_logo_installer__ea_shadow.png"
default = true
    [packages.source]
    name = "github"
    match = "^Windows-Yuzu-EA-[0-9]*.zip$"
        [packages.source.config]
        repo = "pineappleEA/pineapple-src"
    [[packages.shortcuts]]
    name = "yuzu Early Access (PineappleEA)"
    relative_path = "yuzu-windows-msvc-early-access/yuzu.exe"
    description = "Launch yuzu Early Access (PineappleEA)"